-- Migración 005: DEFAULT CURRENT_TIMESTAMP a nivel de MySQL para createdAt/updatedAt
-- en TODAS las tablas del sistema, mismo fix ya aplicado puntualmente a `contratos`
-- en la migración 004 (ver ese archivo para el detalle completo de la causa raíz).
--
-- Resumen: la migración 001 agregó createdAt/updatedAt como DATETIME NULL sin
-- DEFAULT explícito en las 119 tablas del sistema. Confirmado con el log de SQL
-- real: TypeORM envía la palabra clave DEFAULT (no NULL, no omite la columna)
-- para cualquier propiedad no asignada explícitamente en el objeto que se guarda --
-- así que el valor por defecto de la COLUMNA es lo único que decide qué queda
-- guardado. Sin un DEFAULT real, quedaba en NULL. Con CURRENT_TIMESTAMP como
-- default, queda con la fecha real del servidor.
--
-- No borra ni modifica ningún dato existente (los registros ya guardados mantienen
-- su valor actual, sea NULL o una fecha real).

ALTER TABLE `agenda`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `ambito_procedimiento`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `antecedentes`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `auditoria`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bloqueo_registros`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `botones`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `cargos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `causa_externa`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `cierre_caja`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `citas_canceladas`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `citologia`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `clientes`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `compras`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `consentimiento_informado_plantillas`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `contratos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `cotizaciones`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `cuentas_clientes`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `cups`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `datos_adjuntos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `departamentos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `detalle_compra`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `detalle_cotizacion`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `detalle_cuenta_cliente`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `detalle_factura`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `detalle_factura_productos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `detalle_orden`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `detalle_orden_compra`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `detalle_orden_factura`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `detalle_orden_servicio`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `detalle_pago_factura`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `detalle_pago_recibo`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `detalle_registro_anestesia`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `detalle_tarifa`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `detalle_tarifa_productos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `diagnosticos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `documentospdf`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `empleados`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `empresa`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `encabezados`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `endoscopias`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `entidades`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `entrega_resultados`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `equipos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `escala_prader`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `especialidades`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `especialistas`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `especimenes`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `estudios_generados`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `eventos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `examenes_prequirurgicos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `facturas`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `finalidad_consulta`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `finalidad_procedimiento`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `forma_realizacion`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `historia_clinica`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `historia_detalle`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `historia_diagnosticos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `historia_laboratorios`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `historia_medicamentos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `historia_procedimientos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `historia_rxs`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `imagenes`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `imagenes_temporales`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `impresion`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `impresion_detalle_historia`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `impresion_endoscopia`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `impresion_historia`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `impresion_patologia`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `informes`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `ingreso`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `inventario`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `licencias`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `marcas`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `medicamentos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `medios_pago`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `menu`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `motivo_cancelacion_cita`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `municipios`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `optometria`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `orden_compra`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `orden_servicio`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `ordenes`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `ortodoncia`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `patologia`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `percentiles`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `persona_atiende`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `plantillas_informes`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `plantillas_patologia`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `presentacion_productos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `privilegios`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `procedimientos_terapeuticos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `productos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `proveedores`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `recibo_caja`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `registros`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `resoluciones_dian`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `revision_sistemas`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `salones`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `sedes`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `seguimiento_soporte`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `servicios`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `sesiones`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `soporte`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `subentidades`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `submenu`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `tablas`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `tarifa_productos`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `tarifas`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `tipo_afiliado`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `tipo_diagnostico`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `tipo_documento`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `tipo_estudio`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `tipo_identificacion`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `tipo_usuario`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `toma_muestra`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `unidad_medida`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `users`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `usuarios`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `via_administracion`
  MODIFY COLUMN `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
